### ISSUE TITLE
SyntaxError: Unexpected reserved word 'interface'.

### ISSUE THREAD

**Issue by Morriz** [IanVS/prettier-plugin-sort-imports#30]
**Your Environment**

-   **Prettier version**: 2.6.2
-   **node version**: 16.4.2
-   **package manager**: npm@7
-   **IDE**: VScode

**Describe the bug**

after installing this plugin prettier breaks when encountering `interface` construct:
```ts
export interface Props {
  no?: Worky
}
```

Error as in title.

**Comment by IanVS** [comment]
Hi, can you share your prettier config?

**Comment by Morriz** [comment]
sure:
```yaml
---
extends:
  - 'next/core-web-vitals'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
globals:
  React: 'readonly'
plugins:
  - '@typescript-eslint'
rules:
  '@next/next/no-img-element': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: 'none'
      vars: 'all'
  arrow-body-style: warn
  import/no-duplicates: warn
  import/no-useless-path-segments: warn
  no-unused-vars:
    - warn
    - args: 'after-used'
      argsIgnorePattern: '^_'
  react/display-name: off
  react/no-children-prop: off
  react/no-unescaped-entities: off
  react/self-closing-comp: error
  sort-imports:
    - 'error'
    - ignoreDeclarationSort: true

```

**Comment by Morriz** [comment]
sorry that was eslint...might be useful too? Here's the "prettier" one:
```yaml
# proseWrap: always
semi: false
trailingComma: all
singleQuote: true
printWidth: 120
jsxSingleQuote: true
importOrderParserPlugins:
  - classProperties
  - decorators-legacy
```
